#! /bin/sh
#
# atftpd - Script to launch atftpd server.
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/atftpd
NAME=atftpd
DESC="Advanced TFTP server"
PORT=6900
IPADDR=192.168.100.1
LOGFILE="/tmp/atftpd-$USER.log"
LOGLVL=7
PIDFILE="/tmp/atftpd-$USER.pid"
ROOT=$(realpath $(dirname $0)/../out/img)
OPTIONS="$ROOT --maxthread 2 --no-multicast --logfile $LOGFILE --pidfile $PIDFILE"
OPTIONS="$OPTIONS --daemon --user $USER --group $(id -gn) --port $PORT"
OPTIONS="$OPTIONS --bind-address $IPADDR --verbose=$LOGLVL"

test -f $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

touch $LOGFILE

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --oknodo --quiet --exec $DAEMON --pidfile $PIDFILE -- $OPTIONS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON --pidfile $PIDFILE
	echo "$NAME."
	;;
  restart|reload|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON --pidfile $PIDFILE
	sleep 1
	start-stop-daemon --start --oknodo --quiet --exec $DAEMON --pidfile $PIDFILE -- $OPTIONS
	echo "$NAME."
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  *)
	N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
